/// Flutter icons Application1
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Application1
///      fonts:
///       - asset: fonts/Application1.ttf
///
///
///
import 'package:flutter/widgets.dart';

class Application1 {
  Application1._();

  static const _kFontFam = 'Application1';
  static const String _kFontPkg = null;

  static const IconData fish =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData barley =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
